FROM golang:1.21.1-alpine3.18 AS build

WORKDIR /go/src/app
COPY . .

# yeah those are a lot of env variables
ARG SENTRY_DNS=${{ secrets.SENTRY_DNS }}
ARG POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
ARG POSTGRES_USER=${{ secrets.POSTGRES_USER }}
ARG POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
ARG POSTGRES_DB=${{ secrets.POSTGRES_DB }}
ARG POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}

ENV SENTRY_DNS ${SENTRY_DNS}
ENV POSTGRES_HOST ${POSTGRES_HOST}
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}
ENV POSTGRES_PORT ${POSTGRES_PORT}

RUN go mod download
RUN go vet -v
RUN go test -v

RUN CGO_ENABLED=0 go build -o /go/bin/app

# Final stage
FROM gcr.io/distroless/static-debian11

# all env values must be loaded in each stage
ARG SENTRY_DNS=${{ secrets.SENTRY_DNS }}
ARG POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
ARG POSTGRES_USER=${{ secrets.POSTGRES_USER }}
ARG POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
ARG POSTGRES_DB=${{ secrets.POSTGRES_DB }}
ARG POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}

ENV SENTRY_DNS ${SENTRY_DNS}
ENV POSTGRES_HOST ${POSTGRES_HOST}
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}
ENV POSTGRES_PORT ${POSTGRES_PORT}

COPY --from=build /go/bin/app /
CMD ["/app"]